baseURL = "https://blog.kbck.pl/"
languageCode = "en-us"
title = "ðŸ‘€"
theme = "hyde-hyde"
googleAnalytics = "UA-194171347-1"

[params.social]
    twitter = "kbkk_pl"
    github = "kbkk"

[params]
    description = "Jakub Kisielewski's Software Blog"

